### ISSUE TITLE
Switching Axes

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/MicroJournaling#1]
As a user I want to visualize the data in a scatterplot. It is a bar graph right now. 

I need to switch the axes before making it into a scatterplot.

My D3 bar graph responds to real data now. 

I have been working on switching the x and y axes. Also, right now the way the dates are formatted, they are running into the bars.

I know I need to make changes here for the axes:

```
        var x = d3.scale.linear()
        .domain([0, data_max])
        .range([0, w - ( left_margin + right_margin )]),
        y = d3.scale.ordinal()
        .domain(d3.range(data.length))
        .rangeBands([bottom_margin, h - top_margin], .5);

        var chart_top = h - y.rangeBand()/2 - top_margin;
        var chart_bottom = bottom_margin + y.rangeBand()/2;
        var chart_left = left_margin;
        var chart_right = w - right_margin;
```

**Comment by bfellerath** [comment]
Hi everybody,

I wasn't able to solve this issue today. I have spiked with other code that is the type of bar graph that I want but I am having trouble getting it to display my data. My options now are to change the graph that I have (which displays my data but is not organized the way I want it) or to start over with a graph that is organized how I want but I will have to get it to display my data, which is turning out to be a major blocker after today.

I'd appreciate any advice, thanks.

Bryan

**Comment by emilylordahl** [comment]
Saw in this morning's stand up you got this figured out!!! :tada::tada::tada:
